version: "3.2"
services:
  db:
    image: mysql
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
      MYSQL_USER: harmakit
      MYSQL_PASSWORD: password
